export const SEARCH_ONCHANGE = "SEARCH_ONCHANGE";
export const ALL_USERS_DATA = "ALL_USERS_DATA";
export const STORE_SUGGESTIONS = "STORE_SUGGESTIONS";
export const STORE_SUGGESTIONS_DETAILS = "STORE_SUGGESTIONS_DETAILS";
export const STORE_PROFILE_DETAILS = "STORE_PROFILE_DETAILS";
export const STORE_REPO_DETAILS = "STORE_REPO_DETAILS";